export enum PocketStyles {
  CLASSIC = "CLASSIC",
  PITA = "PITA",
  TRAD_X = "TRAD_X",
  STANWICK = "STANWICK",
  O_CHANNEL = "O_CHANNEL",
  RELEASE = "RELEASE",
  LADDER = "LADDER",
  MESH_RUNNER = "MESH_RUNNER",
  MENS_CORNER = "MENS_CORNER",
  SINGLE_TWIST_PITA = "SINGLE_TWIST_PITA"
}
